apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-359715
  artifacts:
    # - image:  us.gcr.io/ticketing-dev-359715/auth
    - image:  alexander2g3/ticketing_auth
      context:  auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image:  alexander2g3/ticketing_client
      context:  client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  '**/*.js'
            dest: .
    - image:  alexander2g3/ticketing_tickets
      context:  tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image:  alexander2g3/ticketing_orders
      context:  orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src:  'src/**/*.ts'
            dest: .
    - image: alexander2g3/ticketing_expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: alexander2g3/ticketing_payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
