name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ee2217f1-6383-4042-89e4-264c8081e48a
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
