name: deploy-manifests

on:
  push:
    branches:
      - master
    paths:
      - 'infra/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          version: 1.38.0
      - run: doctl kubernetes cluster save t-purchases
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
